import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import Providers from "@/lib/query-provider";
import { ThemeSwitcher } from "@/components/theme/ThemeSwitcher";
import LayoutComponent from "@/components/layout/LayoutComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <LayoutComponent>{children}</LayoutComponent>
            {/* <ThemeSwitcher /> */}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
